name: Build Windows Desktop App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-pc-windows-msvc

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'

    - name: Install dependencies
      run: npm install

    - name: Debug environment
      run: |
        echo "Node.js version: $(node --version)"
        echo "npm version: $(npm --version)"  
        echo "Available npm scripts:"
        npm run
        echo "Tauri CLI version:"
        npx tauri --version
        echo "Current directory:"
        Get-Location
        echo "Directory contents:"
        Get-ChildItem

    - name: Build frontend
      run: npm run build

    - name: Build Tauri app
      run: |
        echo "Starting Tauri build..."
        echo "Build environment:"
        echo "TAURI_SIGNING_PRIVATE_KEY is set: $($env:TAURI_SIGNING_PRIVATE_KEY -ne $null)"
        echo "Running command: npm run tauri:build:win"
        npm run tauri:build:win
      env:
        TAURI_SIGNING_PRIVATE_KEY: ""
        TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ""

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: windows-build
        path: |
          src-tauri/target/x86_64-pc-windows-msvc/release/bundle/
          src-tauri/target/x86_64-pc-windows-msvc/release/*.exe
        retention-days: 30
        if-no-files-found: warn
