name: Build Windows Desktop App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-pc-windows-msvc

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'

    - name: Install dependencies
      run: npm install

    - name: Debug environment
      run: |
        Write-Host "Node.js version:"
        node --version
        Write-Host "npm version:"
        npm --version
        Write-Host "Tauri CLI version:"
        npx tauri --version
        Write-Host "Current directory:"
        Get-Location
        Write-Host "Checking dependencies..."
        Test-Path "node_modules"

    - name: Build frontend
      run: |
        Write-Host "Starting frontend build..."
        npm run build
      env:
        CI: true
        NODE_ENV: production

    - name: Verify build output
      run: |
        Write-Host "Checking build output..."
        Test-Path "build"
        if (Test-Path "build") {
          Write-Host "Build directory found"
          Get-ChildItem "build" | Select-Object -First 5
        }

    - name: Build Tauri app
      run: npm run tauri:build:win
      env:
        TAURI_SIGNING_PRIVATE_KEY: ""
        TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ""

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: windows-build
        path: |
          src-tauri/target/x86_64-pc-windows-msvc/release/bundle/
          src-tauri/target/x86_64-pc-windows-msvc/release/*.exe
        retention-days: 30
        if-no-files-found: warn
