name: Build Windows Desktop App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-pc-windows-msvc

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'

    - name: Install dependencies
      run: npm install

    - name: Verify installation
      shell: cmd
      run: |
        echo Verifying npm installation...
        if exist "node_modules" (
          echo node_modules directory exists
          if exist "node_modules\.bin\vite.cmd" (
            echo Vite binary found
          ) else (
            echo Vite binary missing
          )
          if exist "node_modules\@sveltejs" (
            echo SvelteKit found
          ) else (
            echo SvelteKit missing
          )
        ) else (
          echo node_modules directory missing!
        )

    - name: Debug environment
      run: |
        Write-Host "Node.js version:"
        node --version
        Write-Host "npm version:"
        npm --version
        Write-Host "Tauri CLI version:"
        npx tauri --version
        Write-Host "Current directory:"
        Get-Location
        Write-Host "Checking dependencies..."
        Test-Path "node_modules"

    - name: Test npm access
      shell: cmd
      run: |
        echo Testing npm commands...
        npm --version
        echo Testing script access...
        npm run
        echo Available scripts listed above

    - name: Build frontend
      shell: cmd
      run: |
        echo Starting frontend build...
        echo Current directory: %CD%
        echo PATH: %PATH%
        echo Running npm run build...
        npm run build
      env:
        CI: true
        NODE_ENV: production

    - name: Verify build output
      shell: cmd
      run: |
        echo Checking build output...
        if exist "build" (
          echo Build directory found
          dir build
        ) else (
          echo Build directory not found!
        )

    - name: Build Tauri app
      run: npm run tauri:build:win
      env:
        TAURI_SIGNING_PRIVATE_KEY: ""
        TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ""

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: windows-build
        path: |
          src-tauri/target/x86_64-pc-windows-msvc/release/bundle/
          src-tauri/target/x86_64-pc-windows-msvc/release/*.exe
        retention-days: 30
        if-no-files-found: warn
