name: Build Windows Desktop App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-windows:
    runs-on: windows-latest
    
    env:
      TAURI_SIGNING_PRIVATE_KEY: ""
      TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ""
      RUST_BACKTRACE: 1
      CI: true
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-pc-windows-msvc

    - name: Verify Rust installation
      shell: powershell
      run: |
        Write-Host "Verifying Rust installation..."
        rustc --version
        cargo --version
        rustup target list --installed

    - name: Install WebView2
      shell: powershell
      run: |
        Write-Host "Installing Microsoft Edge WebView2..."
        try {
          Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/p/?LinkId=2124703" -OutFile "MicrosoftEdgeWebview2Setup.exe" -UseBasicParsing
          Write-Host "Downloaded WebView2 installer"
          Start-Process -FilePath "MicrosoftEdgeWebview2Setup.exe" -ArgumentList "/silent", "/install" -Wait -NoNewWindow
          Write-Host "WebView2 installation completed"
        } catch {
          Write-Host "WebView2 installation failed, but continuing build as it might already be installed"
          Write-Host $_.Exception.Message
        }

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'

    - name: Install frontend dependencies
      run: npm install

    - name: Verify Tauri CLI
      shell: powershell
      run: |
        Write-Host "Verifying Tauri CLI installation..."
        npx tauri --version
        Write-Host "Checking available Tauri commands..."
        npx tauri --help

    - name: Build frontend
      run: npm run build

    - name: Verify frontend build
      shell: powershell
      run: |
        Write-Host "Checking frontend build output..."
        if (Test-Path "build") {
          Write-Host "Build directory exists"
          Get-ChildItem "build" | Select-Object Name, Length
        } else {
          Write-Host "ERROR: Build directory not found!"
          exit 1
        }

    - name: Build Windows desktop app
      shell: powershell
      run: |
        Write-Host "Starting Tauri build process..."
        Write-Host "Current directory: $(Get-Location)"
        Write-Host "Available npm scripts:"
        npm run --silent
        Write-Host "Running: npm run tauri:build:win"
        
        # Set error handling
        $ErrorActionPreference = "Continue"
        
        try {
          npm run tauri:build:win
          if ($LASTEXITCODE -ne 0) {
            Write-Host "Build failed with exit code $LASTEXITCODE"
            exit $LASTEXITCODE
          }
          Write-Host "Build completed successfully!"
        } catch {
          Write-Host "Build failed with exception: $($_.Exception.Message)"
          Write-Host "Stack trace: $($_.ScriptStackTrace)"
          exit 1
        }

    - name: List build outputs
      shell: powershell
      run: |
        echo "Checking build outputs..."
        if (Test-Path "src-tauri/target/x86_64-pc-windows-msvc/release/bundle") {
          Get-ChildItem -Recurse "src-tauri/target/x86_64-pc-windows-msvc/release/bundle"
        } else {
          echo "Bundle directory not found"
        }
        if (Test-Path "src-tauri/target/x86_64-pc-windows-msvc/release") {
          Get-ChildItem "src-tauri/target/x86_64-pc-windows-msvc/release" -Filter "*.exe"
        } else {
          echo "Release directory not found"
        }

    - name: Upload Windows Installers
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: windows-installers
        path: |
          src-tauri/target/x86_64-pc-windows-msvc/release/bundle/msi/*.msi
          src-tauri/target/x86_64-pc-windows-msvc/release/bundle/nsis/*.exe
        retention-days: 30
        if-no-files-found: warn

    - name: Upload Windows Executable
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: windows-executable
        path: |
          src-tauri/target/x86_64-pc-windows-msvc/release/*.exe
          src-tauri/target/x86_64-pc-windows-msvc/release/app.exe
          src-tauri/target/x86_64-pc-windows-msvc/release/bids-collector.exe
        retention-days: 30
        if-no-files-found: warn

  build-info:
    runs-on: ubuntu-latest
    needs: build-windows
    if: always()
    
    steps:
    - name: Build Summary
      run: |
        echo "## Build Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Windows Build" >> $GITHUB_STEP_SUMMARY
        if [ "${{ needs.build-windows.result }}" == "success" ]; then
          echo "✅ **Success** - Windows desktop app built successfully" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Available Downloads:**" >> $GITHUB_STEP_SUMMARY
          echo "- Windows MSI Installer" >> $GITHUB_STEP_SUMMARY
          echo "- Windows NSIS Installer" >> $GITHUB_STEP_SUMMARY
          echo "- Windows Executable" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ **Failed** - Windows build failed" >> $GITHUB_STEP_SUMMARY
        fi
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Target Platform" >> $GITHUB_STEP_SUMMARY
        echo "- **Platform**: Windows x64" >> $GITHUB_STEP_SUMMARY
        echo "- **Architecture**: x86_64-pc-windows-msvc" >> $GITHUB_STEP_SUMMARY
        echo "- **Bundle Types**: MSI, NSIS" >> $GITHUB_STEP_SUMMARY
